import { randomBytes } from "node:crypto";
import type { CertificateKind } from "@prisma/client";
import { db } from "@/lib/db";
import { CONFERENCE } from "@/lib/conference";

// Certificates are generated by the system, not typed up by hand.
//
// When the registration desk marks a delegate as attended, a certificate row
// is created and a verification code is minted. The certificate itself is
// rendered from that row on request at /certificate/<code>, so there is no PDF
// to store, regenerate or lose, and a reissue is just the same URL again.

/**
 * Crockford base32 without I, L, O or U: no character pairs that get misread
 * when a code is copied off a printed certificate by hand.
 */
const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const CODE_LENGTH = 12;

function randomCode(): string {
  // 12 characters over a 32 symbol alphabet is 60 bits: not enumerable, which
  // is what stops /verify from being used to harvest the delegate register.
  const bytes = randomBytes(CODE_LENGTH);
  let out = "";
  for (let i = 0; i < CODE_LENGTH; i++) out += ALPHABET[bytes[i] % ALPHABET.length];
  return `${out.slice(0, 4)}-${out.slice(4, 8)}-${out.slice(8, 12)}`;
}

/** Accepts a code with or without its dashes, in any case. */
export function normaliseCode(input: string): string {
  const bare = input.trim().toUpperCase().replace(/[^0-9A-Z]/g, "");
  if (bare.length !== CODE_LENGTH) return input.trim().toUpperCase();
  return `${bare.slice(0, 4)}-${bare.slice(4, 8)}-${bare.slice(8, 12)}`;
}

async function uniqueCode(): Promise<string> {
  for (let attempt = 0; attempt < 8; attempt++) {
    const candidate = randomCode();
    const clash = await db.certificate.findUnique({ where: { code: candidate } });
    if (!clash) return candidate;
  }
  throw new Error("Could not mint a unique certificate code");
}

export const CERTIFICATE_LABELS: Record<CertificateKind, string> = {
  ATTENDANCE: "Certificate of Attendance",
  PRESENTATION: "Certificate of Presentation",
  POSTER: "Certificate of Poster Presentation",
  SESSION_CHAIR: "Certificate of Service as Session Chair",
  REVIEWER: "Certificate of Service as Reviewer",
};

export const CERTIFICATE_STATEMENTS: Record<CertificateKind, string> = {
  ATTENDANCE: `attended the ${CONFERENCE.edition} ${CONFERENCE.name}`,
  PRESENTATION: `presented a paper at the ${CONFERENCE.edition} ${CONFERENCE.name}`,
  POSTER: `presented a poster at the ${CONFERENCE.edition} ${CONFERENCE.name}`,
  SESSION_CHAIR: `served as a session chair at the ${CONFERENCE.edition} ${CONFERENCE.name}`,
  REVIEWER: `served as a reviewer for the ${CONFERENCE.edition} ${CONFERENCE.name}`,
};

/**
 * Issues a certificate for a delegate who has been marked as attended.
 * Idempotent: calling it twice for the same delegate and kind returns the
 * certificate that already exists rather than minting a second code.
 */
export async function issueAttendanceCertificate(registrationId: string) {
  const registration = await db.registration.findUnique({ where: { id: registrationId } });
  if (!registration) throw new Error("Registration not found");
  if (registration.status !== "PAID") {
    throw new Error("Certificates are only issued once a registration is paid");
  }
  if (!registration.attended) {
    throw new Error("Certificates are only issued once attendance is recorded");
  }

  const existing = await db.certificate.findFirst({
    where: { registrationId, kind: "ATTENDANCE", revokedAt: null },
  });
  if (existing) return existing;

  return db.certificate.create({
    data: {
      code: await uniqueCode(),
      kind: "ATTENDANCE",
      recipientName: registration.fullName,
      institution: registration.institution,
      registrationId,
    },
  });
}

/**
 * Issues a presentation or poster certificate for an accepted submission.
 * The kind follows what the author actually did, which the Secretariat sets
 * when the programme is finalised.
 */
export async function issuePresentationCertificate(
  submissionId: string,
  kind: Extract<CertificateKind, "PRESENTATION" | "POSTER"> = "PRESENTATION"
) {
  const submission = await db.submission.findUnique({ where: { id: submissionId } });
  if (!submission) throw new Error("Submission not found");
  if (submission.status !== "ACCEPTED") {
    throw new Error("Presentation certificates are only issued for accepted submissions");
  }

  const existing = await db.certificate.findFirst({
    where: { submissionId, kind, revokedAt: null },
  });
  if (existing) return existing;

  return db.certificate.create({
    data: {
      code: await uniqueCode(),
      kind,
      recipientName: submission.authorName,
      institution: submission.institution,
      paperTitle: submission.title,
      track: submission.track,
      submissionId,
    },
  });
}

/** Issues an ad hoc certificate, for chairs and reviewers who are not delegates. */
export async function issueServiceCertificate(input: {
  kind: Extract<CertificateKind, "SESSION_CHAIR" | "REVIEWER">;
  recipientName: string;
  institution?: string;
  track?: string;
}) {
  return db.certificate.create({
    data: {
      code: await uniqueCode(),
      kind: input.kind,
      recipientName: input.recipientName,
      institution: input.institution,
      track: input.track,
    },
  });
}

export interface CertificateView {
  code: string;
  kind: CertificateKind;
  label: string;
  statement: string;
  recipientName: string;
  institution: string | null;
  paperTitle: string | null;
  track: string | null;
  issuedAt: Date;
  revoked: boolean;
  revokedReason: string | null;
}

export async function lookupCertificate(rawCode: string): Promise<CertificateView | null> {
  const code = normaliseCode(rawCode);
  const record = await db.certificate.findUnique({ where: { code } });
  if (!record) return null;

  return {
    code: record.code,
    kind: record.kind,
    label: CERTIFICATE_LABELS[record.kind],
    statement: CERTIFICATE_STATEMENTS[record.kind],
    recipientName: record.recipientName,
    institution: record.institution,
    paperTitle: record.paperTitle,
    track: record.track,
    issuedAt: record.issuedAt,
    revoked: record.revokedAt !== null,
    revokedReason: record.revokedReason,
  };
}

/**
 * Finds the certificates belonging to one person, keyed on the email and
 * reference they were given at registration or submission. Requiring both
 * means an email address on its own is not enough to pull someone's records.
 */
export async function certificatesForHolder(email: string, reference: string) {
  const cleanEmail = email.trim().toLowerCase();
  const cleanRef = reference.trim().toUpperCase();

  const registration = await db.registration.findUnique({
    where: { reference: cleanRef },
    include: { certificates: { where: { revokedAt: null } } },
  });
  if (registration && registration.email.toLowerCase() === cleanEmail) {
    return registration.certificates;
  }

  const submission = await db.submission.findUnique({
    where: { reference: cleanRef },
    include: { certificates: { where: { revokedAt: null } } },
  });
  if (submission && submission.email.toLowerCase() === cleanEmail) {
    return submission.certificates;
  }

  return [];
}
