import type { Metadata } from "next";
import Link from "next/link";
import { CertificateLookup } from "@/components/CertificateLookup";
import { IconPattern } from "@/components/IconPattern";
import { AcademicIcon } from "@/components/icons/AcademicIcons";
import type { AcademicIconName } from "@/components/icons/AcademicIcons";
import { CERTIFICATE_LABELS } from "@/lib/certificates";
import { CONFERENCE, CONTACT } from "@/lib/conference";

export const metadata: Metadata = {
  title: "Certificates | 19th UNILAG Annual Research Conference",
  description:
    "How certificates are issued for the 19th UNILAG Annual Research Conference, how to collect yours, and how anyone can verify one.",
};

const HOW_IT_WORKS: { icon: AcademicIconName; title: string; body: string }[] = [
  {
    icon: "users",
    title: "You are checked in at the desk",
    body: "Quote your registration reference at the desk on arrival. That single action is what records your attendance, and nothing else needs to happen.",
  },
  {
    icon: "seal",
    title: "The certificate is generated at once",
    body: "A certificate is created the moment attendance is recorded, carrying your name, your institution, and a verification code unique to you. No queue, no forms, no waiting until the closing session.",
  },
  {
    icon: "mail",
    title: "A link arrives by email",
    body: "The link goes to the address you registered with. You can also find it here at any time using that address and your reference.",
  },
  {
    icon: "shield",
    title: "Anyone can check it is genuine",
    body: "The code on the certificate resolves against this site, so a promotion panel or a funder can confirm it without writing to the Secretariat.",
  },
];

const KINDS: { kind: keyof typeof CERTIFICATE_LABELS; body: string }[] = [
  { kind: "ATTENDANCE", body: "For every registered delegate checked in at the desk." },
  { kind: "PRESENTATION", body: "For authors who present a paper in a session." },
  { kind: "POSTER", body: "For authors who present a poster at the research fair." },
  { kind: "SESSION_CHAIR", body: "For colleagues who chair a session." },
  { kind: "REVIEWER", body: "For colleagues who review abstracts for a track." },
];

export default function CertificatesPage() {
  return (
    <>
      <section className="page-hero">
        <div className="wrap">
          <div className="eyebrow">Afterwards</div>
          <h1 className="page-title">Certificates</h1>
          <p className="page-lede">
            Certificates for the {CONFERENCE.edition} edition are generated by the system, not typed
            up by hand, and they carry a code anybody can verify. Nothing has to be collected in
            person.
          </p>
        </div>
      </section>

      <section className="how-section">
        <IconPattern variant="dense" opacity={0.05} className="section-pattern" />
        <div className="wrap">
          <div className="section-head">
            <div className="eyebrow">How it works</div>
            <h2>From the registration desk to your file, in four steps</h2>
          </div>
          <ol className="how-list">
            {HOW_IT_WORKS.map((step, index) => (
              <li key={step.title}>
                <span className="how-index mono">{String(index + 1).padStart(2, "0")}</span>
                <span className="how-icon">
                  <AcademicIcon name={step.icon} size={24} />
                </span>
                <div>
                  <h3>{step.title}</h3>
                  <p>{step.body}</p>
                </div>
              </li>
            ))}
          </ol>
        </div>
      </section>

      <section id="collect">
        <div className="wrap">
          <div className="section-head">
            <div className="eyebrow">Collect</div>
            <h2>Find your certificate</h2>
            <p>
              Enter the email address you registered or submitted with, and the reference code you
              were given. Both are needed: an email address on its own would let anyone pull another
              delegate&rsquo;s records.
            </p>
          </div>

          <CertificateLookup />
        </div>
      </section>

      <section>
        <div className="wrap">
          <div className="section-head">
            <div className="eyebrow">What is issued</div>
            <h2>Five kinds of certificate</h2>
          </div>
          <ul className="kind-list">
            {KINDS.map((item) => (
              <li key={item.kind}>
                <AcademicIcon name="scroll" size={20} />
                <div>
                  <h3>{CERTIFICATE_LABELS[item.kind]}</h3>
                  <p>{item.body}</p>
                </div>
              </li>
            ))}
          </ul>

          <p className="archive-note">
            Verifying someone else&rsquo;s certificate? Go to{" "}
            <Link href="/verify">the verification page</Link>. Something missing or a name spelled
            wrong? Write to <a href={`mailto:${CONTACT.email}`}>{CONTACT.email}</a> with your
            reference and the Secretariat will reissue it.
          </p>
        </div>
      </section>
    </>
  );
}
